Update docker-compose.dev.yml
Wrong indentation causes error
> ERROR: In file '.\docker-compose.dev.yml', service 'environment' must be a mapping not an array.